### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by kkieffer** [blacksmithdevelopers/MGRSConverter#1]
@johnayers84  Since the project https://www.movable-type.co.uk/scripts/latlong-utm-mgrs.html has the MIT license, does this project also carry the MIT license?

**Comment by johnayers84** [comment]
@kkieffer We have not assigned a license to it.  Given the source of it, if you want to fork it under the MIT license, we have no objections.  Long term, we'll likely return the repository to a private repo.

**Comment by johnayers84** [comment]
Added MIT license.
